# Sunshine Optimal Settings Script
# Run as Administrator on Windows VM

Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Sunshine GameStream Optimizer" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Check for admin privileges
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[ERROR] Please run this script as Administrator" -ForegroundColor Red
    exit 1
}

# 1. Set High Performance Power Plan
Write-Host "[INFO] Setting High Performance power plan..." -ForegroundColor Blue
powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
Write-Host "[OK] Power plan set to High Performance" -ForegroundColor Green

# 2. Disable Xbox Game Bar and Game DVR
Write-Host "[INFO] Disabling Xbox Game Bar..." -ForegroundColor Blue
try {
    Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR" -Name "AppCaptureEnabled" -Value 0 -ErrorAction SilentlyContinue
    Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR" -Name "GameDVR_Enabled" -Value 0 -ErrorAction SilentlyContinue
    Set-ItemProperty -Path "HKCU:\System\GameConfigStore" -Name "GameDVR_Enabled" -Value 0 -ErrorAction SilentlyContinue
    Write-Host "[OK] Xbox Game Bar disabled" -ForegroundColor Green
} catch {
    Write-Host "[WARN] Could not fully disable Game Bar" -ForegroundColor Yellow
}

# 3. Configure Windows Firewall for Sunshine
Write-Host "[INFO] Configuring Windows Firewall..." -ForegroundColor Blue

# Remove old rules if they exist
Remove-NetFirewallRule -DisplayName "Sunshine *" -ErrorAction SilentlyContinue

# Add new rules
New-NetFirewallRule -DisplayName "Sunshine TCP" -Direction Inbound -Protocol TCP -LocalPort 47984-47990 -Action Allow -Profile Any | Out-Null
New-NetFirewallRule -DisplayName "Sunshine UDP Control" -Direction Inbound -Protocol UDP -LocalPort 47984-47990 -Action Allow -Profile Any | Out-Null
New-NetFirewallRule -DisplayName "Sunshine UDP Video" -Direction Inbound -Protocol UDP -LocalPort 48010 -Action Allow -Profile Any | Out-Null
Write-Host "[OK] Firewall rules configured" -ForegroundColor Green

# 4. Disable Nagle's Algorithm for lower latency
Write-Host "[INFO] Optimizing network settings for low latency..." -ForegroundColor Blue
$adapters = Get-NetAdapter | Where-Object {$_.Status -eq "Up"}
foreach ($adapter in $adapters) {
    $regPath = "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\$($adapter.InterfaceGuid)"
    Set-ItemProperty -Path $regPath -Name "TcpAckFrequency" -Value 1 -ErrorAction SilentlyContinue
    Set-ItemProperty -Path $regPath -Name "TCPNoDelay" -Value 1 -ErrorAction SilentlyContinue
}
Write-Host "[OK] Network latency optimizations applied" -ForegroundColor Green

# 5. Create optimized Sunshine config
Write-Host "[INFO] Creating optimized Sunshine configuration..." -ForegroundColor Blue

$sunshineConfigDir = "$env:ProgramData\Sunshine"
$sunshineConfig = "$sunshineConfigDir\sunshine.conf"

# Backup existing config
if (Test-Path $sunshineConfig) {
    $backupPath = "$sunshineConfig.backup.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item $sunshineConfig $backupPath
    Write-Host "[INFO] Backed up existing config to: $backupPath" -ForegroundColor Blue
}

# Optimal settings for RTX 3060
$optimalConfig = @"
# Sunshine Optimal Configuration for RTX 3060
# Generated by setup-sunshine-optimal.ps1

# Encoder Settings
encoder = nvenc
capture = nvfbc
adapter_name = NVIDIA GeForce RTX 3060

# Frame Settings
frame_limiter_enable = true
frame_limiter_disable_vsync = true

# NVENC Quality Settings (Low Latency High Quality)
nvenc_preset = 1
nvenc_spatial_aq = enabled
nvenc_coder = auto
nvenc_rc = cbr

# Audio
audio_sink = Audio Sink
virtual_sink = Steam Virtual Audio Sink

# Network (SECURE: LAN only for web UI, no UPnP)
origin_web_ui_allowed = lan
upnp = disabled
address_family = both
lan_encryption_mode = 1

# Resolution/Refresh Mapping (supports both 1080p and 1440p)
dd_mode_remapping = {"mixed":[{"final_refresh_rate":"60","final_resolution":"1920x1080","requested_fps":"60","requested_resolution":"1920x1080"},{"final_refresh_rate":"60","final_resolution":"2560x1440","requested_fps":"60","requested_resolution":"2560x1440"},{"final_refresh_rate":"144","final_resolution":"1920x1080","requested_fps":"144","requested_resolution":"1920x1080"}],"refresh_rate_only":[],"resolution_only":[]}

# Frame Queue (lower = less latency)
fec_percentage = 20

# Misc
status = true
min_log_level = 1
dd_config_revert_on_disconnect = enabled
key_rightalt_to_key_win = enabled
"@

# Only write if directory exists (Sunshine is installed)
if (Test-Path $sunshineConfigDir) {
    $optimalConfig | Out-File -FilePath $sunshineConfig -Encoding utf8
    Write-Host "[OK] Sunshine config updated" -ForegroundColor Green
} else {
    Write-Host "[WARN] Sunshine config directory not found. Is Sunshine installed?" -ForegroundColor Yellow
}

# 6. Summary
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Optimization Complete!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Applied Settings:" -ForegroundColor White
Write-Host "    - High Performance power plan" -ForegroundColor Gray
Write-Host "    - Xbox Game Bar disabled" -ForegroundColor Gray
Write-Host "    - Firewall rules for Sunshine (47984-47990, 48010)" -ForegroundColor Gray
Write-Host "    - Network latency optimizations (Nagle disabled)" -ForegroundColor Gray
Write-Host "    - Sunshine config with NVENC + NVFBC" -ForegroundColor Gray
Write-Host ""
Write-Host "  Next Steps:" -ForegroundColor Yellow
Write-Host "    1. Restart Sunshine service or reboot" -ForegroundColor Gray
Write-Host "    2. In NVIDIA Control Panel:" -ForegroundColor Gray
Write-Host "       - Power management: Prefer maximum performance" -ForegroundColor Gray
Write-Host "       - Low Latency Mode: Ultra" -ForegroundColor Gray
Write-Host "    3. In Moonlight client:" -ForegroundColor Gray
Write-Host "       - Resolution: 1920x1080" -ForegroundColor Gray
Write-Host "       - FPS: 60" -ForegroundColor Gray
Write-Host "       - Bitrate: 40 Mbps (LAN) / 20 Mbps (WAN)" -ForegroundColor Gray
Write-Host "       - Codec: HEVC" -ForegroundColor Gray
Write-Host ""
Write-Host "  Restart Sunshine now? (Press any key or Ctrl+C to skip)"
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

# Try to restart Sunshine service
$sunshineSvc = Get-Service -Name "Sunshine*" -ErrorAction SilentlyContinue
if ($sunshineSvc) {
    Write-Host "[INFO] Restarting Sunshine service..." -ForegroundColor Blue
    Restart-Service -Name $sunshineSvc.Name -Force
    Write-Host "[OK] Sunshine restarted" -ForegroundColor Green
} else {
    Write-Host "[INFO] Sunshine service not found. Please restart manually via system tray." -ForegroundColor Yellow
}
