#!/usr/bin/env python3
"""
AI-Powered Test Generator - Actually Writes Test Files
"""
import os
import re
from pathlib import Path
from typing import List, Dict

class AITestGenerator:
    """Generate tests and write to files"""
    
    def __init__(self):
        self.generated_dir = Path("tests/generated")
        self.test_manifest = Path("tests/generated/MANIFEST.txt")
    
    def scan_flask_routes(self, app_file: str) -> List[Dict]:
        """Scan Flask app for routes"""
        routes = []
        try:
            with open(app_file, 'r') as f:
                content = f.read()
                pattern = r'@(?:app|bp)\.route\(["\']([^"\']+)["\']\)'
                matches = re.findall(pattern, content)
                for route in matches:
                    routes.append({
                        'path': route,
                        'type': 'api' if '/api/' in route else 'page',
                        'name': route.strip('/').replace('/', '_').replace('-', '_') or 'index'
                    })
        except Exception as e:
            print(f"Error scanning {app_file}: {e}")
        return routes
    
    def generate_test_file(self, service_name: str, routes: List[Dict]) -> str:
        """Generate complete test file"""
        test_code = f'''"""
Auto-generated tests for {service_name}
Generated by AI Test Generator
"""
import pytest
from app import app

class TestGenerated{service_name.title().replace('-', '')}:
    """Auto-generated test cases"""
    
    @pytest.fixture
    def client(self):
        app.config['TESTING'] = True
        with app.test_client() as client:
            yield client
'''
        
        for route in routes:
            test_code += f'''
    def test_{route['name']}(self, client):
        """Test {route['path']}"""
        response = client.get('{route['path']}')
        assert response.status_code in [200, 302, 401, 404]
'''
        
        return test_code
    
    def write_tests(self, service_path: str, service_name: str):
        """Write generated tests to file"""
        output_dir = Path(service_path) / "tests" / "generated"
        output_dir.mkdir(parents=True, exist_ok=True)
        
        app_file = Path(service_path) / "app.py"
        if not app_file.exists():
            print(f"No app.py found in {service_path}")
            return
        
        routes = self.scan_flask_routes(str(app_file))
        
        if not routes:
            print(f"No routes found in {app_file}")
            return
        
        test_code = self.generate_test_file(service_name, routes)
        
        output_file = output_dir / f"test_{service_name}_generated.py"
        with open(output_file, 'w') as f:
            f.write(test_code)
        
        print(f"✅ Generated {len(routes)} tests in {output_file}")
        
        manifest_file = output_dir / "MANIFEST.txt"
        with open(manifest_file, 'a') as f:
            f.write(f"{service_name}: {len(routes)} routes generated\n")

if __name__ == "__main__":
    generator = AITestGenerator()
    
    print("🤖 AI Test Generator - Writing Test Files")
    print("=" * 60)
    
    generator.write_tests('services/dashboard', 'dashboard')
    
    print("\n✅ Test generation complete!")
