# ============================================
# DISCORD BOT SERVICE BUNDLE
# Discord ticket management bot
# ============================================


services:
  # ============================================
  # Discord Bot
  # ============================================
  discord-bot:
    build:
      context: ../services/discord-bot
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    depends_on:
      homelab-postgres:
        condition: service_healthy
    networks:
      - homelab
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ${DEPLOYMENT_PATH:-.}/.env
      - ${DEPLOYMENT_PATH:-.}/.env.discord-bot
    environment:
      DATABASE_URL: "postgresql://ticketbot:${DISCORD_DB_PASSWORD}@homelab-postgres:5432/ticketbot"
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      VITE_DISCORD_CLIENT_ID: ${VITE_DISCORD_CLIENT_ID}
      DISCORD_CALLBACK_URL: https://bot.rig-city.com/auth/discord/callback
      APP_URL: https://bot.rig-city.com
      PUBLIC_DOMAIN: https://bot.rig-city.com
      VITE_CUSTOM_WS_URL: ${VITE_CUSTOM_WS_URL:-}
      SESSION_SECRET: ${DISCORD_SESSION_SECRET}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      RESET_DB: ${RESET_DB:-false}
    volumes:
      - ../services/discord-bot/attached_assets:/app/attached_assets
      - ../services/discord-bot/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
