# ============================================
# STREAM BOT SERVICE BUNDLE
# Twitch/YouTube streaming bot with AI
# ============================================


services:
  # ============================================
  # Stream Bot (Snapple Facts AI)
  # ============================================
  stream-bot:
    build:
      context: ../services/stream-bot
      dockerfile: Dockerfile
    container_name: stream-bot
    restart: unless-stopped
    networks:
      - homelab
    depends_on:
      homelab-postgres:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ${DEPLOYMENT_PATH:-.}/.env
      - ${DEPLOYMENT_PATH:-.}/.env.stream-bot
    environment:
      DATABASE_URL: postgresql://streambot:${STREAMBOT_DB_PASSWORD}@homelab-postgres:5432/streambot
      SESSION_SECRET: ${STREAMBOT_SESSION_SECRET}
      OPENAI_API_KEY: ${STREAMBOT_OPENAI_API_KEY:-${OPENAI_API_KEY}}
      OPENAI_BASE_URL: ${STREAMBOT_OPENAI_BASE_URL:-https://api.openai.com/v1}
      STREAMBOT_FACT_MODEL: gpt-4o-mini
      NODE_ENV: ${STREAMBOT_NODE_ENV:-production}
      PORT: ${STREAMBOT_PORT:-5000}
      HOST: 0.0.0.0
      APP_URL: https://stream.rig-city.com
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      TWITCH_REDIRECT_URI: ${TWITCH_REDIRECT_URI:-https://stream.rig-city.com/api/auth/twitch/callback}
      TWITCH_SIGNIN_CALLBACK_URL: https://stream.rig-city.com/api/auth/twitch/callback
      YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID:-}
      YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET:-}
      YOUTUBE_REFRESH_TOKEN: ${YOUTUBE_REFRESH_TOKEN:-}
      YOUTUBE_REDIRECT_URI: ${YOUTUBE_REDIRECT_URI:-https://stream.rig-city.com/api/auth/youtube/callback}
      YOUTUBE_SIGNIN_CALLBACK_URL: https://stream.rig-city.com/api/auth/youtube/callback
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID:-}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET:-}
      SPOTIFY_REFRESH_TOKEN: ${SPOTIFY_REFRESH_TOKEN:-}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI:-https://stream.rig-city.com/api/auth/spotify/callback}
      KICK_CLIENT_ID: ${KICK_CLIENT_ID:-}
      KICK_CLIENT_SECRET: ${KICK_CLIENT_SECRET:-}
      KICK_REDIRECT_URI: ${KICK_REDIRECT_URI:-https://stream.rig-city.com/api/auth/kick/callback}
      KICK_SIGNIN_CALLBACK_URL: https://stream.rig-city.com/api/auth/kick/callback
      SERVICE_AUTH_TOKEN: ${SERVICE_AUTH_TOKEN}
    volumes:
      - ../services/stream-bot/logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
